### ISSUE TITLE
Using pvlib / mosmix for an enphase-array setup

### ISSUE THREAD

**Issue by olikra** [StefaE/PVForecast#21]
Hi Stefan,

thanks for this repo. It's one of the clearest implementations bringing mosmix and pvlib together, Helped me a lot.

I try to setup this system for following use case (which differs a bit from "normal" pv-systems): My sister will get an enphase-system. In enphase each module has his own inverter. So we get installed 26 modules with 26 individual inverters. These 26 modules will be arranged (the roof is a little bit labyrinthine) in following way:

**Arrays:**
EAST: 8 modules/inverters
WEST1: 2 modules/inverters
SOUTH1: 2 modules/inverters
SOUTH2:6 modules/inverters
WEST2: 8 modules/inverters

In a normal setup this would be arranged by strings to inverter and pvlib can handle it. 

What is the best way to handle the 26 indivdual module/inverters? Simulate each module/inverter by an individual run (so 26 loops with individual azimuths/tilts?
**update:** Or calculating one module/inverter per array (tilt is the same in the array) and multiplying the result by number of module/invert in the specific array
Thanks upfront.

**Comment by StefaE** [comment]
Hi Olikra,

you can define [split array configurations](https://github.com/StefaE/PVForecast#split-array-system-configuration). `PVForecast` then makes a forecast for each split and sums them up to a total.

Whether I'd define 26 splits, I doubt - but probably five for the five arrays you list (or potentially even average out WEST1/WEST2 and SOUTH1/SOUTH2, depending how different they are ...

Not sure why you split SOUTH and WEST ... it could be because of shading. Unfortunately, `pvlib` has no easy way (afaik) to convey shading information from any sort of horizon information ... so you'd in this case overestimate production.  (`pvlib` has an [open issue](https://github.com/pvlib/pvlib-python/issues/1290) on this)

**Comment by olikra** [comment]
@StefaE The split results out of the planned mounting of the panels by the installer. Having different array-split-setups inside enphases system and "my" forecasting is not the best to get it in sync. I can change the panel/array/azimuth at any time. But this should get synced in Enphse and "my" system.
